template_path: ConfigLogAggregation.j2
stack_name: ConfigLogAggregation
sceptre_user_data:
  stackname: !stack_name
  config_bucket: !stack_output_external essentials::AWSS3ConfigBucket
  accounts:
    - !ssm /infra/AdmincentralAwsAccountId
    - !ssm /infra/BridgeDevAwsAccountId
    - !ssm /infra/BridgeProdAwsAccountId
    - !ssm /infra/ScicompAwsAccountId
    - !ssm /infra/SynapseProdAwsAccountId
    - !ssm /infra/SynapseDevAwsAccountId
    - !ssm /infra/SynapseDwAwsAccountId
    - !ssm /infra/SageItAwsAccountId
    - !ssm /infra/OrganizationsAwsAccountId
    - !ssm /infra/SandboxAwsAccountId
    - !ssm /infra/SecuritycentralAwsAccountId
    - !ssm /infra/ItSandboxAwsAccountId
    - !ssm /infra/ImagecentralAwsAccountId
