template_path: templates/ConfigLogAggregation.yaml
stack_name: ConfigLogAggregation
parameters:
  AdmincentralAwsAccountId: !ssm /infra/AdmincentralAwsAccountId
  BridgeDevAwsAccountId: !ssm /infra/BridgeDevAwsAccountId
  BridgeProdAwsAccountId: !ssm /infra/BridgeProdAwsAccountId
  ScicompAwsAccountId: !ssm /infra/ScicompAwsAccountId
  SynapseProdAwsAccountId: !ssm /infra/SynapseProdAwsAccountId
  SynapseDevAwsAccountId: !ssm /infra/SynapseDevAwsAccountId
  SynapseDwAwsAccountId: !ssm /infra/SynapseDwAwsAccountId
  SageItAwsAccountId: !ssm /infra/SageItAwsAccountId
  OrganizationsAwsAccountId: !ssm /infra/OrganizationsAwsAccountId
