template_path: templates/GuardDutyMaster.yaml
stack_name: guardduty-master
dependencies:
  - essentials
parameters:
  BridgeProdAwsAccountId: "{{ environment_variable.BridgeProdAwsAccountId }}"
  SynapseProdAwsAccountId: "{{ environment_variable.SynapseProdAwsAccountId }}"
  OperatorEmail: {{ environment_variable.OperatorEmail }}
