template_path: remote-templates/peer-route-config.yaml
stack_name: peer-vpc-admincentral
parameters:
  PeeringConnectionId: pcx-8715e2ef
  VpcPrivateRouteTable: rtb-ec2d8390
  VpcPublicRouteTable: rtb-3556f849
  VpnCidr: 10.1.0.0/16
hooks:
  before_update:
    - !cmd "aws --profile {{ var.profile }} s3 cp s3://{{ environment_variable.AdminCentralInfraCfBucket }}/aws-infra/master/peer-route-config.yaml ./remote-templates/peer-route-config.yaml"
