template_path: tester.j2
stack_name: stack1
sceptre_user_data:
  stackname: !stack_name
  cloudtrail_bucket: !stack_output_external essentials::AWSS3CloudtrailBucket
  accounts:
    - !ssm /infra/AdmincentralAwsAccountId
    - !ssm /infra/BridgeDevAwsAccountId
    - !ssm /infra/BridgeProdAwsAccountId
    - !ssm /infra/ScicompAwsAccountId
    - !ssm /infra/SynapseProdAwsAccountId
    - !ssm /infra/SynapseDevAwsAccountId
    - !ssm /infra/SynapseDwAwsAccountId
    - !ssm /infra/SageItAwsAccountId
    - !ssm /infra/OrganizationsAwsAccountId
    - !ssm /infra/SandboxAwsAccountId
    - !ssm /infra/SecuritycentralAwsAccountId
