template_path: remote-templates/vpc.yaml
stack_name: vpc
parameters:
  VpcSubnetPrefix: "10.6"
  VpcName: sagevpc
hooks:
  before_update:
    - !cmd "aws --profile {{ var.profile }} s3 cp s3://{{ environment_variable.AdminCentralInfraCfBucket }}/aws-infra/master/vpc.yaml ./remote-templates/vpc.yaml"
