sudo: false
language: python
python: 3.5
cache: pip
fast_finish: true
install:
- ./setup_git_crypt.sh
- openssl aes-256-cbc -K $encrypted_625ae79b2f0d_key -iv $encrypted_625ae79b2f0d_iv -in git-crypt.key.enc -out git-crypt.key -d
- /tmp/git-crypt-master/git-crypt unlock ./git-crypt.key
- rm -rf git-crypt.key
- source env_vars && source env_vars.secret
- /tmp/git-crypt-master/git-crypt lock
- ./setup_aws_cli.sh
- pip install sceptre
script:
- ./validate-templates.sh || travis_terminate 1
- sceptre --var "profile=default" --var "region=us-east-1" launch-env prod
